// ========================================
// NEXUS — Plans Catalog
// ========================================

import {
  CAPABILITIES
} from "./capabilities.js";


// ========================================
// PLAN STATUS
// ========================================

export const PLAN_STATUS = {

  ACTIVE:
    "active",

  INACTIVE:
    "inactive"

};


// ========================================
// PLAN IDS
// ========================================

export const PLAN_IDS = {

  FREE:
    "free",

  PRO:
    "pro",

  PREMIUM:
    "premium"

};


// ========================================
// PLANS
// ========================================

export const PLANS = {

  [PLAN_IDS.FREE]: {

    id:
      PLAN_IDS.FREE,

    name:
      "Free",

    description:
      "Acceso básico a NEXUS.",

    status:
      PLAN_STATUS.ACTIVE,

    capabilities: [

      CAPABILITIES.ACCOUNT_PROFILE_VIEW,
      CAPABILITIES.ACCOUNT_PROFILE_EDIT,

      CAPABILITIES.ACCOUNT_SECURITY_MANAGE,

      CAPABILITIES.ACCOUNT_NOTIFICATIONS_VIEW,

      CAPABILITIES.ACCOUNT_SETTINGS_MANAGE,

      CAPABILITIES.ACCOUNT_ENTITIES_MANAGE,

      CAPABILITIES.ENTITY_VIEW,

      CAPABILITIES.TEAM_VIEW,
      CAPABILITIES.PLAYER_VIEW,

      CAPABILITIES.TOURNAMENT_VIEW,
      CAPABILITIES.LEAGUE_VIEW,

      CAPABILITIES.MATCH_VIEW,

      CAPABILITIES.STATISTICS_VIEW

    ]

  },


  [PLAN_IDS.PRO]: {

    id:
      PLAN_IDS.PRO,

    name:
      "Pro",

    description:
      "Herramientas avanzadas para gestionar una entidad competitiva.",

    status:
      PLAN_STATUS.ACTIVE,

    capabilities: [

      // ACCOUNT

      CAPABILITIES.ACCOUNT_PROFILE_VIEW,
      CAPABILITIES.ACCOUNT_PROFILE_EDIT,

      CAPABILITIES.ACCOUNT_SECURITY_MANAGE,

      CAPABILITIES.ACCOUNT_NOTIFICATIONS_VIEW,

      CAPABILITIES.ACCOUNT_SETTINGS_MANAGE,

      CAPABILITIES.ACCOUNT_ENTITIES_MANAGE,


      // ENTITY

      CAPABILITIES.ENTITY_VIEW,
      CAPABILITIES.ENTITY_EDIT,


      // TEAM

      CAPABILITIES.TEAM_VIEW,
      CAPABILITIES.TEAM_EDIT,

      CAPABILITIES.TEAM_ROSTER_VIEW,
      CAPABILITIES.TEAM_ROSTER_MANAGE,


      // PLAYER

      CAPABILITIES.PLAYER_VIEW,
      CAPABILITIES.PLAYER_EDIT,


      // TOURNAMENT

      CAPABILITIES.TOURNAMENT_VIEW,
      CAPABILITIES.TOURNAMENT_CREATE,
      CAPABILITIES.TOURNAMENT_EDIT,
      CAPABILITIES.TOURNAMENT_MANAGE,

      CAPABILITIES.TOURNAMENT_PARTICIPANTS_MANAGE,
      CAPABILITIES.TOURNAMENT_ROSTER_MANAGE,

      CAPABILITIES.TOURNAMENT_SEEDING_MANAGE,
      CAPABILITIES.TOURNAMENT_BRACKET_MANAGE,

      CAPABILITIES.TOURNAMENT_CHECKIN_MANAGE,


      // LEAGUE

      CAPABILITIES.LEAGUE_VIEW,
      CAPABILITIES.LEAGUE_CREATE,
      CAPABILITIES.LEAGUE_EDIT,
      CAPABILITIES.LEAGUE_MANAGE,

      CAPABILITIES.LEAGUE_SEASON_MANAGE,
      CAPABILITIES.LEAGUE_DIVISION_MANAGE,
      CAPABILITIES.LEAGUE_MATCHDAY_MANAGE,

      CAPABILITIES.LEAGUE_STANDINGS_MANAGE,
      CAPABILITIES.LEAGUE_PLAYOFFS_MANAGE,


      // MATCHES

      CAPABILITIES.MATCH_VIEW,
      CAPABILITIES.MATCH_MANAGE,

      CAPABILITIES.MATCH_RESULT_MANAGE,
      CAPABILITIES.MATCH_EVIDENCE_MANAGE,


      // STATISTICS

      CAPABILITIES.STATISTICS_VIEW,
      CAPABILITIES.STATISTICS_ADVANCED_VIEW,

      CAPABILITIES.ANALYTICS_VIEW,


      // CUSTOMIZATION

      CAPABILITIES.CUSTOM_BRANDING,


      // INTEGRATIONS

      CAPABILITIES.INTEGRATIONS_VIEW

    ]

  },


  [PLAN_IDS.PREMIUM]: {

    id:
      PLAN_IDS.PREMIUM,

    name:
      "Premium",

    description:
      "Acceso completo a las herramientas avanzadas de NEXUS.",

    status:
      PLAN_STATUS.ACTIVE,

    capabilities: [

      // ACCOUNT

      CAPABILITIES.ACCOUNT_PROFILE_VIEW,
      CAPABILITIES.ACCOUNT_PROFILE_EDIT,

      CAPABILITIES.ACCOUNT_SECURITY_MANAGE,

      CAPABILITIES.ACCOUNT_NOTIFICATIONS_VIEW,

      CAPABILITIES.ACCOUNT_SETTINGS_MANAGE,

      CAPABILITIES.ACCOUNT_ENTITIES_MANAGE,


      // ENTITY

      CAPABILITIES.ENTITY_VIEW,
      CAPABILITIES.ENTITY_EDIT,


      // TEAM

      CAPABILITIES.TEAM_VIEW,
      CAPABILITIES.TEAM_EDIT,

      CAPABILITIES.TEAM_ROSTER_VIEW,
      CAPABILITIES.TEAM_ROSTER_MANAGE,


      // PLAYER

      CAPABILITIES.PLAYER_VIEW,
      CAPABILITIES.PLAYER_EDIT,


      // TOURNAMENT

      CAPABILITIES.TOURNAMENT_VIEW,
      CAPABILITIES.TOURNAMENT_CREATE,
      CAPABILITIES.TOURNAMENT_EDIT,
      CAPABILITIES.TOURNAMENT_MANAGE,

      CAPABILITIES.TOURNAMENT_PARTICIPANTS_MANAGE,
      CAPABILITIES.TOURNAMENT_ROSTER_MANAGE,

      CAPABILITIES.TOURNAMENT_SEEDING_MANAGE,
      CAPABILITIES.TOURNAMENT_BRACKET_MANAGE,

      CAPABILITIES.TOURNAMENT_CHECKIN_MANAGE,


      // LEAGUE

      CAPABILITIES.LEAGUE_VIEW,
      CAPABILITIES.LEAGUE_CREATE,
      CAPABILITIES.LEAGUE_EDIT,
      CAPABILITIES.LEAGUE_MANAGE,

      CAPABILITIES.LEAGUE_SEASON_MANAGE,
      CAPABILITIES.LEAGUE_DIVISION_MANAGE,
      CAPABILITIES.LEAGUE_MATCHDAY_MANAGE,

      CAPABILITIES.LEAGUE_STANDINGS_MANAGE,
      CAPABILITIES.LEAGUE_PLAYOFFS_MANAGE,


      // MATCHES

      CAPABILITIES.MATCH_VIEW,
      CAPABILITIES.MATCH_MANAGE,

      CAPABILITIES.MATCH_RESULT_MANAGE,
      CAPABILITIES.MATCH_EVIDENCE_MANAGE,


      // STATISTICS

      CAPABILITIES.STATISTICS_VIEW,
      CAPABILITIES.STATISTICS_ADVANCED_VIEW,

      CAPABILITIES.ANALYTICS_VIEW,


      // CUSTOMIZATION

      CAPABILITIES.CUSTOM_BRANDING,


      // INTEGRATIONS

      CAPABILITIES.INTEGRATIONS_VIEW,
      CAPABILITIES.INTEGRATIONS_MANAGE

    ]

  }

};